# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tes.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1374, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblYaw = QtWidgets.QLabel(self.centralwidget)
        self.lblYaw.setGeometry(QtCore.QRect(60, 90, 120, 21))
        self.lblYaw.setWordWrap(False)
        self.lblYaw.setObjectName("lblYaw")
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        self.lblStatus.setGeometry(QtCore.QRect(820, 90, 120, 21))
        self.lblStatus.setWordWrap(False)
        self.lblStatus.setObjectName("lblStatus")
        self.lblRoll = QtWidgets.QLabel(self.centralwidget)
        self.lblRoll.setGeometry(QtCore.QRect(420, 90, 120, 21))
        self.lblRoll.setWordWrap(False)
        self.lblRoll.setObjectName("lblRoll")
        self.lblDepth = QtWidgets.QLabel(self.centralwidget)
        self.lblDepth.setGeometry(QtCore.QRect(610, 90, 120, 21))
        self.lblDepth.setWordWrap(False)
        self.lblDepth.setObjectName("lblDepth")
        self.lblSetpoint = QtWidgets.QLabel(self.centralwidget)
        self.lblSetpoint.setGeometry(QtCore.QRect(1080, 100, 120, 21))
        self.lblSetpoint.setWordWrap(False)
        self.lblSetpoint.setObjectName("lblSetpoint")
        self.lblPitch = QtWidgets.QLabel(self.centralwidget)
        self.lblPitch.setGeometry(QtCore.QRect(240, 90, 120, 21))
        self.lblPitch.setWordWrap(False)
        self.lblPitch.setObjectName("lblPitch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1374, 26))
        self.menubar.setObjectName("menubar")
        self.menuCek_sensor = QtWidgets.QMenu(self.menubar)
        self.menuCek_sensor.setObjectName("menuCek_sensor")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCek_sensor.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblYaw.setText(_translate("MainWindow", "lblYaw"))
        self.lblStatus.setText(_translate("MainWindow", "lblStatus"))
        self.lblRoll.setText(_translate("MainWindow", "lblRoll"))
        self.lblDepth.setText(_translate("MainWindow", "lblDepth"))
        self.lblSetpoint.setText(_translate("MainWindow", "lblSetpoint"))
        self.lblPitch.setText(_translate("MainWindow", "lblPitch"))
        self.menuCek_sensor.setTitle(_translate("MainWindow", "Sensor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())