# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rov_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        
        # Set gradient background stylesheet
        MainWindow.setStyleSheet("""
            QMainWindow {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(102, 126, 234, 255),
                    stop:0.5 rgba(118, 75, 162, 255),
                    stop:1 rgba(240, 147, 251, 255));
            }
        """)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background: transparent;")
        
        # ========== HEADER ==========
        self.headerFrame = QtWidgets.QFrame(self.centralwidget)
        self.headerFrame.setGeometry(QtCore.QRect(20, 20, 1360, 100))
        self.headerFrame.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 80);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
        """)
        self.headerFrame.setObjectName("headerFrame")
        
        self.lblHeader = QtWidgets.QLabel(self.headerFrame)
        self.lblHeader.setGeometry(QtCore.QRect(0, 0, 1360, 100))
        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 32px;
                font-weight: bold;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblHeader.setObjectName("lblHeader")
        
        # ========== SENSOR CARDS ==========
        # Yaw Card
        self.cardYaw = QtWidgets.QFrame(self.centralwidget)
        self.cardYaw.setGeometry(QtCore.QRect(20, 140, 330, 200))
        self.cardYaw.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 80);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
            QFrame:hover {
                background-color: rgba(255, 255, 255, 100);
                border: 1px solid rgba(255, 255, 255, 80);
            }
        """)
        self.cardYaw.setObjectName("cardYaw")
        
        self.lblYawIcon = QtWidgets.QLabel(self.cardYaw)
        self.lblYawIcon.setGeometry(QtCore.QRect(0, 20, 330, 50))
        self.lblYawIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblYawIcon.setStyleSheet("""
            QLabel {
                font-size: 40px;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawIcon.setObjectName("lblYawIcon")
        
        self.lblYawLabel = QtWidgets.QLabel(self.cardYaw)
        self.lblYawLabel.setGeometry(QtCore.QRect(0, 75, 330, 20))
        self.lblYawLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblYawLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 230);
                font-size: 12px;
                font-weight: bold;
                letter-spacing: 2px;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawLabel.setObjectName("lblYawLabel")
        
        self.lblYawValue = QtWidgets.QLabel(self.cardYaw)
        self.lblYawValue.setGeometry(QtCore.QRect(0, 100, 330, 60))
        self.lblYawValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblYawValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 42px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawValue.setObjectName("lblYawValue")
        
        self.lblYawUnit = QtWidgets.QLabel(self.cardYaw)
        self.lblYawUnit.setGeometry(QtCore.QRect(0, 165, 330, 20))
        self.lblYawUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblYawUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                font-weight: 500;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawUnit.setObjectName("lblYawUnit")
        
        # Depth Card
        self.cardDepth = QtWidgets.QFrame(self.centralwidget)
        self.cardDepth.setGeometry(QtCore.QRect(365, 140, 330, 200))
        self.cardDepth.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 80);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
            QFrame:hover {
                background-color: rgba(255, 255, 255, 100);
                border: 1px solid rgba(255, 255, 255, 80);
            }
        """)
        self.cardDepth.setObjectName("cardDepth")
        
        self.lblDepthIcon = QtWidgets.QLabel(self.cardDepth)
        self.lblDepthIcon.setGeometry(QtCore.QRect(0, 20, 330, 50))
        self.lblDepthIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDepthIcon.setStyleSheet("""
            QLabel {
                font-size: 40px;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthIcon.setObjectName("lblDepthIcon")
        
        self.lblDepthLabel = QtWidgets.QLabel(self.cardDepth)
        self.lblDepthLabel.setGeometry(QtCore.QRect(0, 75, 330, 20))
        self.lblDepthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDepthLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 230);
                font-size: 12px;
                font-weight: bold;
                letter-spacing: 2px;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthLabel.setObjectName("lblDepthLabel")
        
        self.lblDepthValue = QtWidgets.QLabel(self.cardDepth)
        self.lblDepthValue.setGeometry(QtCore.QRect(0, 100, 330, 60))
        self.lblDepthValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDepthValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 42px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthValue.setObjectName("lblDepthValue")
        
        self.lblDepthUnit = QtWidgets.QLabel(self.cardDepth)
        self.lblDepthUnit.setGeometry(QtCore.QRect(0, 165, 330, 20))
        self.lblDepthUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDepthUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                font-weight: 500;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthUnit.setObjectName("lblDepthUnit")
        
        # Roll Card
        self.cardRoll = QtWidgets.QFrame(self.centralwidget)
        self.cardRoll.setGeometry(QtCore.QRect(710, 140, 330, 200))
        self.cardRoll.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 80);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
            QFrame:hover {
                background-color: rgba(255, 255, 255, 100);
                border: 1px solid rgba(255, 255, 255, 80);
            }
        """)
        self.cardRoll.setObjectName("cardRoll")
        
        self.lblRollIcon = QtWidgets.QLabel(self.cardRoll)
        self.lblRollIcon.setGeometry(QtCore.QRect(0, 20, 330, 50))
        self.lblRollIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRollIcon.setStyleSheet("""
            QLabel {
                font-size: 40px;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollIcon.setObjectName("lblRollIcon")
        
        self.lblRollLabel = QtWidgets.QLabel(self.cardRoll)
        self.lblRollLabel.setGeometry(QtCore.QRect(0, 75, 330, 20))
        self.lblRollLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRollLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 230);
                font-size: 12px;
                font-weight: bold;
                letter-spacing: 2px;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollLabel.setObjectName("lblRollLabel")
        
        self.lblRollValue = QtWidgets.QLabel(self.cardRoll)
        self.lblRollValue.setGeometry(QtCore.QRect(0, 100, 330, 60))
        self.lblRollValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRollValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 42px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollValue.setObjectName("lblRollValue")
        
        self.lblRollUnit = QtWidgets.QLabel(self.cardRoll)
        self.lblRollUnit.setGeometry(QtCore.QRect(0, 165, 330, 20))
        self.lblRollUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRollUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                font-weight: 500;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollUnit.setObjectName("lblRollUnit")
        
        # Pitch Card
        self.cardPitch = QtWidgets.QFrame(self.centralwidget)
        self.cardPitch.setGeometry(QtCore.QRect(1055, 140, 330, 200))
        self.cardPitch.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 80);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
            QFrame:hover {
                background-color: rgba(255, 255, 255, 100);
                border: 1px solid rgba(255, 255, 255, 80);
            }
        """)
        self.cardPitch.setObjectName("cardPitch")
        
        self.lblPitchIcon = QtWidgets.QLabel(self.cardPitch)
        self.lblPitchIcon.setGeometry(QtCore.QRect(0, 20, 330, 50))
        self.lblPitchIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPitchIcon.setStyleSheet("""
            QLabel {
                font-size: 40px;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchIcon.setObjectName("lblPitchIcon")
        
        self.lblPitchLabel = QtWidgets.QLabel(self.cardPitch)
        self.lblPitchLabel.setGeometry(QtCore.QRect(0, 75, 330, 20))
        self.lblPitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPitchLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 230);
                font-size: 12px;
                font-weight: bold;
                letter-spacing: 2px;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchLabel.setObjectName("lblPitchLabel")
        
        self.lblPitchValue = QtWidgets.QLabel(self.cardPitch)
        self.lblPitchValue.setGeometry(QtCore.QRect(0, 100, 330, 60))
        self.lblPitchValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPitchValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 42px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchValue.setObjectName("lblPitchValue")
        
        self.lblPitchUnit = QtWidgets.QLabel(self.cardPitch)
        self.lblPitchUnit.setGeometry(QtCore.QRect(0, 165, 330, 20))
        self.lblPitchUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPitchUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                font-weight: 500;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchUnit.setObjectName("lblPitchUnit")
        
        # ========== TAB WIDGET CONTROL ==========
        self.controlFrame = QtWidgets.QFrame(self.centralwidget)
        self.controlFrame.setGeometry(QtCore.QRect(20, 360, 1360, 490))
        self.controlFrame.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 80);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
        """)
        self.controlFrame.setObjectName("controlFrame")
        
        self.tabWidget = QtWidgets.QTabWidget(self.controlFrame)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 1300, 430))
        self.tabWidget.setStyleSheet("""
            QTabWidget::pane {
                border: none;
                background: transparent;
            }
            QTabBar::tab {
                background-color: rgba(255, 255, 255, 100);
                color: rgba(255, 255, 255, 200);
                padding: 14px 28px;
                margin-right: 10px;
                border-top-left-radius: 15px;
                border-top-right-radius: 15px;
                font-size: 12px;
                font-weight: bold;
                letter-spacing: 1px;
                border: 1px solid rgba(255, 255, 255, 51);
            }
            QTabBar::tab:selected {
                background-color: rgba(255, 255, 255, 150);
                color: white;
                border: 1px solid rgba(255, 255, 255, 102);
            }
            QTabBar::tab:hover {
                background-color: rgba(255, 255, 255, 128);
            }
        """)
        self.tabWidget.setObjectName("tabWidget")
        
        # ========== YAW CONTROL TAB ==========
        self.tabYaw = QtWidgets.QWidget()
        self.tabYaw.setObjectName("tabYaw")
        self.tabYaw.setStyleSheet("background: transparent;")
        
        self.frameYawControl = QtWidgets.QFrame(self.tabYaw)
        self.frameYawControl.setGeometry(QtCore.QRect(20, 20, 1260, 350))
        self.frameYawControl.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 60);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
        """)
        self.frameYawControl.setObjectName("frameYawControl")
        
        self.lblYawControlTitle = QtWidgets.QLabel(self.frameYawControl)
        self.lblYawControlTitle.setGeometry(QtCore.QRect(30, 20, 1200, 40))
        self.lblYawControlTitle.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 20px;
                font-weight: bold;
                letter-spacing: 1.5px;
                background: transparent;
                border: none;
                padding-bottom: 15px;
                border-bottom: 1px solid rgba(255, 255, 255, 51);
            }
        """)
        self.lblYawControlTitle.setObjectName("lblYawControlTitle")
        
        # Info Box - Current Value
        self.frameYawInfo = QtWidgets.QFrame(self.frameYawControl)
        self.frameYawInfo.setGeometry(QtCore.QRect(30, 80, 590, 150))
        self.frameYawInfo.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.frameYawInfo.setObjectName("frameYawInfo")
        
        self.lblYawCurrentLabel = QtWidgets.QLabel(self.frameYawInfo)
        self.lblYawCurrentLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblYawCurrentLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawCurrentLabel.setObjectName("lblYawCurrentLabel")
        
        self.lblYawCurrentValue = QtWidgets.QLabel(self.frameYawInfo)
        self.lblYawCurrentValue.setGeometry(QtCore.QRect(20, 50, 550, 50))
        self.lblYawCurrentValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 36px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawCurrentValue.setObjectName("lblYawCurrentValue")
        
        self.lblYawCurrentUnit = QtWidgets.QLabel(self.frameYawInfo)
        self.lblYawCurrentUnit.setGeometry(QtCore.QRect(20, 110, 550, 20))
        self.lblYawCurrentUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawCurrentUnit.setObjectName("lblYawCurrentUnit")
        
        # Input Box - Setpoint
        self.frameYawInput = QtWidgets.QFrame(self.frameYawControl)
        self.frameYawInput.setGeometry(QtCore.QRect(640, 80, 590, 150))
        self.frameYawInput.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.frameYawInput.setObjectName("frameYawInput")
        
        self.lblYawSetpointLabel = QtWidgets.QLabel(self.frameYawInput)
        self.lblYawSetpointLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblYawSetpointLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawSetpointLabel.setObjectName("lblYawSetpointLabel")
        
        self.txtYawSetpoint = QtWidgets.QLineEdit(self.frameYawInput)
        self.txtYawSetpoint.setGeometry(QtCore.QRect(20, 55, 550, 70))
        self.txtYawSetpoint.setStyleSheet("""
            QLineEdit {
                background-color: rgba(255, 255, 255, 100);
                color: white;
                border: 1px solid rgba(255, 255, 255, 76);
                border-radius: 12px;
                padding: 15px 20px;
                font-size: 18px;
                font-weight: 500;
            }
            QLineEdit:focus {
                border: 1px solid rgba(255, 255, 255, 153);
                background-color: rgba(255, 255, 255, 128);
            }
        """)
        self.txtYawSetpoint.setObjectName("txtYawSetpoint")
        
        # Activate Button
        self.btnYawActivate = QtWidgets.QPushButton(self.frameYawControl)
        self.btnYawActivate.setGeometry(QtCore.QRect(30, 250, 1200, 60))
        self.btnYawActivate.setStyleSheet("""
            QPushButton {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(102, 126, 234, 255),
                    stop:1 rgba(118, 75, 162, 255));
                color: white;
                border: none;
                border-radius: 15px;
                font-size: 14px;
                font-weight: bold;
                letter-spacing: 1.5px;
            }
            QPushButton:hover {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(118, 142, 250, 255),
                    stop:1 rgba(134, 91, 178, 255));
            }
            QPushButton:pressed {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(86, 110, 218, 255),
                    stop:1 rgba(102, 59, 146, 255));
            }
        """)
        self.btnYawActivate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnYawActivate.setObjectName("btnYawActivate")
        
        # Status Label
        self.lblYawStatus = QtWidgets.QLabel(self.frameYawControl)
        self.lblYawStatus.setGeometry(QtCore.QRect(30, 320, 1200, 20))
        self.lblYawStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblYawStatus.setStyleSheet("""
            QLabel {
                color: #ff6b9d;
                font-size: 13px;
                font-weight: bold;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblYawStatus.setObjectName("lblYawStatus")
        
        self.tabWidget.addTab(self.tabYaw, "")
        
        # ========== DEPTH CONTROL TAB ==========
        self.tabDepth = QtWidgets.QWidget()
        self.tabDepth.setObjectName("tabDepth")
        self.tabDepth.setStyleSheet("background: transparent;")
        
        self.frameDepthControl = QtWidgets.QFrame(self.tabDepth)
        self.frameDepthControl.setGeometry(QtCore.QRect(20, 20, 1260, 350))
        self.frameDepthControl.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 60);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
        """)
        self.frameDepthControl.setObjectName("frameDepthControl")
        
        self.lblDepthControlTitle = QtWidgets.QLabel(self.frameDepthControl)
        self.lblDepthControlTitle.setGeometry(QtCore.QRect(30, 20, 1200, 40))
        self.lblDepthControlTitle.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 20px;
                font-weight: bold;
                letter-spacing: 1.5px;
                background: transparent;
                border: none;
                padding-bottom: 15px;
                border-bottom: 1px solid rgba(255, 255, 255, 51);
            }
        """)
        self.lblDepthControlTitle.setObjectName("lblDepthControlTitle")
        
        self.frameDepthInfo = QtWidgets.QFrame(self.frameDepthControl)
        self.frameDepthInfo.setGeometry(QtCore.QRect(30, 80, 590, 150))
        self.frameDepthInfo.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.frameDepthInfo.setObjectName("frameDepthInfo")
        
        self.lblDepthCurrentLabel = QtWidgets.QLabel(self.frameDepthInfo)
        self.lblDepthCurrentLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblDepthCurrentLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthCurrentLabel.setObjectName("lblDepthCurrentLabel")
        
        self.lblDepthCurrentValue = QtWidgets.QLabel(self.frameDepthInfo)
        self.lblDepthCurrentValue.setGeometry(QtCore.QRect(20, 50, 550, 50))
        self.lblDepthCurrentValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 36px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthCurrentValue.setObjectName("lblDepthCurrentValue")
        
        self.lblDepthCurrentUnit = QtWidgets.QLabel(self.frameDepthInfo)
        self.lblDepthCurrentUnit.setGeometry(QtCore.QRect(20, 110, 550, 20))
        self.lblDepthCurrentUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthCurrentUnit.setObjectName("lblDepthCurrentUnit")
        
        self.frameDepthInput = QtWidgets.QFrame(self.frameDepthControl)
        self.frameDepthInput.setGeometry(QtCore.QRect(640, 80, 590, 150))
        self.frameDepthInput.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.frameDepthInput.setObjectName("frameDepthInput")
        
        self.lblDepthSetpointLabel = QtWidgets.QLabel(self.frameDepthInput)
        self.lblDepthSetpointLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblDepthSetpointLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthSetpointLabel.setObjectName("lblDepthSetpointLabel")
        
        self.txtDepthSetpoint = QtWidgets.QLineEdit(self.frameDepthInput)
        self.txtDepthSetpoint.setGeometry(QtCore.QRect(20, 55, 550, 70))
        self.txtDepthSetpoint.setStyleSheet("""
            QLineEdit {
                background-color: rgba(255, 255, 255, 100);
                color: white;
                border: 1px solid rgba(255, 255, 255, 76);
                border-radius: 12px;
                padding: 15px 20px;
                font-size: 18px;
                font-weight: 500;
            }
            QLineEdit:focus {
                border: 1px solid rgba(255, 255, 255, 153);
                background-color: rgba(255, 255, 255, 128);
            }
        """)
        self.txtDepthSetpoint.setObjectName("txtDepthSetpoint")
        
        self.btnDepthActivate = QtWidgets.QPushButton(self.frameDepthControl)
        self.btnDepthActivate.setGeometry(QtCore.QRect(30, 250, 1200, 60))
        self.btnDepthActivate.setStyleSheet("""
            QPushButton {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(102, 126, 234, 255),
                    stop:1 rgba(118, 75, 162, 255));
                color: white;
                border: none;
                border-radius: 15px;
                font-size: 14px;
                font-weight: bold;
                letter-spacing: 1.5px;
            }
            QPushButton:hover {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(118, 142, 250, 255),
                    stop:1 rgba(134, 91, 178, 255));
            }
            QPushButton:pressed {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(86, 110, 218, 255),
                    stop:1 rgba(102, 59, 146, 255));
            }
        """)
        self.btnDepthActivate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDepthActivate.setObjectName("btnDepthActivate")
        
        self.lblDepthStatus = QtWidgets.QLabel(self.frameDepthControl)
        self.lblDepthStatus.setGeometry(QtCore.QRect(30, 320, 1200, 20))
        self.lblDepthStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDepthStatus.setStyleSheet("""
            QLabel {
                color: #ff6b9d;
                font-size: 13px;
                font-weight: bold;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblDepthStatus.setObjectName("lblDepthStatus")
        
        self.tabWidget.addTab(self.tabDepth, "")
        
        # ========== ROLL CONTROL TAB ==========
        self.tabRoll = QtWidgets.QWidget()
        self.tabRoll.setObjectName("tabRoll")
        self.tabRoll.setStyleSheet("background: transparent;")
        
        self.frameRollControl = QtWidgets.QFrame(self.tabRoll)
        self.frameRollControl.setGeometry(QtCore.QRect(20, 20, 1260, 350))
        self.frameRollControl.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 60);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
        """)
        self.frameRollControl.setObjectName("frameRollControl")
        
        self.lblRollControlTitle = QtWidgets.QLabel(self.frameRollControl)
        self.lblRollControlTitle.setGeometry(QtCore.QRect(30, 20, 1200, 40))
        self.lblRollControlTitle.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 20px;
                font-weight: bold;
                letter-spacing: 1.5px;
                background: transparent;
                border: none;
                padding-bottom: 15px;
                border-bottom: 1px solid rgba(255, 255, 255, 51);
            }
        """)
        self.lblRollControlTitle.setObjectName("lblRollControlTitle")
        
        self.frameRollInfo = QtWidgets.QFrame(self.frameRollControl)
        self.frameRollInfo.setGeometry(QtCore.QRect(30, 80, 590, 150))
        self.frameRollInfo.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.frameRollInfo.setObjectName("frameRollInfo")
        
        self.lblRollCurrentLabel = QtWidgets.QLabel(self.frameRollInfo)
        self.lblRollCurrentLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblRollCurrentLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollCurrentLabel.setObjectName("lblRollCurrentLabel")
        
        self.lblRollCurrentValue = QtWidgets.QLabel(self.frameRollInfo)
        self.lblRollCurrentValue.setGeometry(QtCore.QRect(20, 50, 550, 50))
        self.lblRollCurrentValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 36px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollCurrentValue.setObjectName("lblRollCurrentValue")
        
        self.lblRollCurrentUnit = QtWidgets.QLabel(self.frameRollInfo)
        self.lblRollCurrentUnit.setGeometry(QtCore.QRect(20, 110, 550, 20))
        self.lblRollCurrentUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollCurrentUnit.setObjectName("lblRollCurrentUnit")
        
        self.frameRollInput = QtWidgets.QFrame(self.frameRollControl)
        self.frameRollInput.setGeometry(QtCore.QRect(640, 80, 590, 150))
        self.frameRollInput.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.frameRollInput.setObjectName("frameRollInput")
        
        self.lblRollSetpointLabel = QtWidgets.QLabel(self.frameRollInput)
        self.lblRollSetpointLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblRollSetpointLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollSetpointLabel.setObjectName("lblRollSetpointLabel")
        
        self.txtRollSetpoint = QtWidgets.QLineEdit(self.frameRollInput)
        self.txtRollSetpoint.setGeometry(QtCore.QRect(20, 55, 550, 70))
        self.txtRollSetpoint.setStyleSheet("""
            QLineEdit {
                background-color: rgba(255, 255, 255, 100);
                color: white;
                border: 1px solid rgba(255, 255, 255, 76);
                border-radius: 12px;
                padding: 15px 20px;
                font-size: 18px;
                font-weight: 500;
            }
            QLineEdit:focus {
                border: 1px solid rgba(255, 255, 255, 153);
                background-color: rgba(255, 255, 255, 128);
            }
        """)
        self.txtRollSetpoint.setObjectName("txtRollSetpoint")
        
        self.btnRollActivate = QtWidgets.QPushButton(self.frameRollControl)
        self.btnRollActivate.setGeometry(QtCore.QRect(30, 250, 1200, 60))
        self.btnRollActivate.setStyleSheet("""
            QPushButton {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(102, 126, 234, 255),
                    stop:1 rgba(118, 75, 162, 255));
                color: white;
                border: none;
                border-radius: 15px;
                font-size: 14px;
                font-weight: bold;
                letter-spacing: 1.5px;
            }
            QPushButton:hover {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(118, 142, 250, 255),
                    stop:1 rgba(134, 91, 178, 255));
            }
            QPushButton:pressed {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(86, 110, 218, 255),
                    stop:1 rgba(102, 59, 146, 255));
            }
        """)
        self.btnRollActivate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRollActivate.setObjectName("btnRollActivate")
        
        self.lblRollStatus = QtWidgets.QLabel(self.frameRollControl)
        self.lblRollStatus.setGeometry(QtCore.QRect(30, 320, 1200, 20))
        self.lblRollStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRollStatus.setStyleSheet("""
            QLabel {
                color: #ff6b9d;
                font-size: 13px;
                font-weight: bold;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblRollStatus.setObjectName("lblRollStatus")
        
        self.tabWidget.addTab(self.tabRoll, "")
        
        # ========== PITCH CONTROL TAB ==========
        self.tabPitch = QtWidgets.QWidget()
        self.tabPitch.setObjectName("tabPitch")
        self.tabPitch.setStyleSheet("background: transparent;")
        
        self.framePitchControl = QtWidgets.QFrame(self.tabPitch)
        self.framePitchControl.setGeometry(QtCore.QRect(20, 20, 1260, 350))
        self.framePitchControl.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 60);
                border: 1px solid rgba(255, 255, 255, 51);
                border-radius: 20px;
            }
        """)
        self.framePitchControl.setObjectName("framePitchControl")
        
        self.lblPitchControlTitle = QtWidgets.QLabel(self.framePitchControl)
        self.lblPitchControlTitle.setGeometry(QtCore.QRect(30, 20, 1200, 40))
        self.lblPitchControlTitle.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 20px;
                font-weight: bold;
                letter-spacing: 1.5px;
                background: transparent;
                border: none;
                padding-bottom: 15px;
                border-bottom: 1px solid rgba(255, 255, 255, 51);
            }
        """)
        self.lblPitchControlTitle.setObjectName("lblPitchControlTitle")
        
        self.framePitchInfo = QtWidgets.QFrame(self.framePitchControl)
        self.framePitchInfo.setGeometry(QtCore.QRect(30, 80, 590, 150))
        self.framePitchInfo.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.framePitchInfo.setObjectName("framePitchInfo")
        
        self.lblPitchCurrentLabel = QtWidgets.QLabel(self.framePitchInfo)
        self.lblPitchCurrentLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblPitchCurrentLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchCurrentLabel.setObjectName("lblPitchCurrentLabel")
        
        self.lblPitchCurrentValue = QtWidgets.QLabel(self.framePitchInfo)
        self.lblPitchCurrentValue.setGeometry(QtCore.QRect(20, 50, 550, 50))
        self.lblPitchCurrentValue.setStyleSheet("""
            QLabel {
                color: white;
                font-size: 36px;
                font-weight: bold;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchCurrentValue.setObjectName("lblPitchCurrentValue")
        
        self.lblPitchCurrentUnit = QtWidgets.QLabel(self.framePitchInfo)
        self.lblPitchCurrentUnit.setGeometry(QtCore.QRect(20, 110, 550, 20))
        self.lblPitchCurrentUnit.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 180);
                font-size: 12px;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchCurrentUnit.setObjectName("lblPitchCurrentUnit")
        
        self.framePitchInput = QtWidgets.QFrame(self.framePitchControl)
        self.framePitchInput.setGeometry(QtCore.QRect(640, 80, 590, 150))
        self.framePitchInput.setStyleSheet("""
            QFrame {
                background-color: rgba(255, 255, 255, 50);
                border: 1px solid rgba(255, 255, 255, 38);
                border-radius: 15px;
            }
        """)
        self.framePitchInput.setObjectName("framePitchInput")
        
        self.lblPitchSetpointLabel = QtWidgets.QLabel(self.framePitchInput)
        self.lblPitchSetpointLabel.setGeometry(QtCore.QRect(20, 20, 550, 20))
        self.lblPitchSetpointLabel.setStyleSheet("""
            QLabel {
                color: rgba(255, 255, 255, 200);
                font-size: 12px;
                font-weight: 600;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchSetpointLabel.setObjectName("lblPitchSetpointLabel")
        
        self.txtPitchSetpoint = QtWidgets.QLineEdit(self.framePitchInput)
        self.txtPitchSetpoint.setGeometry(QtCore.QRect(20, 55, 550, 70))
        self.txtPitchSetpoint.setStyleSheet("""
            QLineEdit {
                background-color: rgba(255, 255, 255, 100);
                color: white;
                border: 1px solid rgba(255, 255, 255, 76);
                border-radius: 12px;
                padding: 15px 20px;
                font-size: 18px;
                font-weight: 500;
            }
            QLineEdit:focus {
                border: 1px solid rgba(255, 255, 255, 153);
                background-color: rgba(255, 255, 255, 128);
            }
        """)
        self.txtPitchSetpoint.setObjectName("txtPitchSetpoint")
        
        self.btnPitchActivate = QtWidgets.QPushButton(self.framePitchControl)
        self.btnPitchActivate.setGeometry(QtCore.QRect(30, 250, 1200, 60))
        self.btnPitchActivate.setStyleSheet("""
            QPushButton {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(102, 126, 234, 255),
                    stop:1 rgba(118, 75, 162, 255));
                color: white;
                border: none;
                border-radius: 15px;
                font-size: 14px;
                font-weight: bold;
                letter-spacing: 1.5px;
            }
            QPushButton:hover {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(118, 142, 250, 255),
                    stop:1 rgba(134, 91, 178, 255));
            }
            QPushButton:pressed {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 rgba(86, 110, 218, 255),
                    stop:1 rgba(102, 59, 146, 255));
            }
        """)
        self.btnPitchActivate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPitchActivate.setObjectName("btnPitchActivate")
        
        self.lblPitchStatus = QtWidgets.QLabel(self.framePitchControl)
        self.lblPitchStatus.setGeometry(QtCore.QRect(30, 320, 1200, 20))
        self.lblPitchStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPitchStatus.setStyleSheet("""
            QLabel {
                color: #ff6b9d;
                font-size: 13px;
                font-weight: bold;
                letter-spacing: 1px;
                background: transparent;
                border: none;
            }
        """)
        self.lblPitchStatus.setObjectName("lblPitchStatus")
        
        self.tabWidget.addTab(self.tabPitch, "")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ROV Control System - ROS2"))
        
        # Header
        self.lblHeader.setText(_translate("MainWindow", "🤖 Underwater ROV Control System"))
        
        # Sensor Cards
        self.lblYawIcon.setText(_translate("MainWindow", "🧭"))
        self.lblYawLabel.setText(_translate("MainWindow", "YAW"))
        self.lblYawValue.setText(_translate("MainWindow", "0.00"))
        self.lblYawUnit.setText(_translate("MainWindow", "degrees"))
        
        self.lblDepthIcon.setText(_translate("MainWindow", "🌊"))
        self.lblDepthLabel.setText(_translate("MainWindow", "DEPTH"))
        self.lblDepthValue.setText(_translate("MainWindow", "0.00"))
        self.lblDepthUnit.setText(_translate("MainWindow", "meters"))
        
        self.lblRollIcon.setText(_translate("MainWindow", "🔄"))
        self.lblRollLabel.setText(_translate("MainWindow", "ROLL"))
        self.lblRollValue.setText(_translate("MainWindow", "0.00"))
        self.lblRollUnit.setText(_translate("MainWindow", "degrees"))
        
        self.lblPitchIcon.setText(_translate("MainWindow", "⬆️"))
        self.lblPitchLabel.setText(_translate("MainWindow", "PITCH"))
        self.lblPitchValue.setText(_translate("MainWindow", "0.00"))
        self.lblPitchUnit.setText(_translate("MainWindow", "degrees"))
        
        # Yaw Control Tab
        self.lblYawControlTitle.setText(_translate("MainWindow", "🧭 Set Yaw Setpoint"))
        self.lblYawCurrentLabel.setText(_translate("MainWindow", "CURRENT VALUE"))
        self.lblYawCurrentValue.setText(_translate("MainWindow", "0.00"))
        self.lblYawCurrentUnit.setText(_translate("MainWindow", "degrees"))
        self.lblYawSetpointLabel.setText(_translate("MainWindow", "TARGET SETPOINT"))
        self.txtYawSetpoint.setPlaceholderText(_translate("MainWindow", "Masukkan nilai yaw..."))
        self.btnYawActivate.setText(_translate("MainWindow", "🚀 ACTIVATE YAW CONTROL"))
        self.lblYawStatus.setText(_translate("MainWindow", "⚪ STATUS: INACTIVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabYaw), _translate("MainWindow", "YAW CONTROL"))
        
        # Depth Control Tab
        self.lblDepthControlTitle.setText(_translate("MainWindow", "🌊 Set Depth Setpoint"))
        self.lblDepthCurrentLabel.setText(_translate("MainWindow", "CURRENT VALUE"))
        self.lblDepthCurrentValue.setText(_translate("MainWindow", "0.00"))
        self.lblDepthCurrentUnit.setText(_translate("MainWindow", "meters"))
        self.lblDepthSetpointLabel.setText(_translate("MainWindow", "TARGET SETPOINT"))
        self.txtDepthSetpoint.setPlaceholderText(_translate("MainWindow", "Masukkan nilai depth..."))
        self.btnDepthActivate.setText(_translate("MainWindow", "🚀 ACTIVATE DEPTH CONTROL"))
        self.lblDepthStatus.setText(_translate("MainWindow", "⚪ STATUS: INACTIVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDepth), _translate("MainWindow", "DEPTH CONTROL"))
        
        # Roll Control Tab
        self.lblRollControlTitle.setText(_translate("MainWindow", "🔄 Set Roll Setpoint"))
        self.lblRollCurrentLabel.setText(_translate("MainWindow", "CURRENT VALUE"))
        self.lblRollCurrentValue.setText(_translate("MainWindow", "0.00"))
        self.lblRollCurrentUnit.setText(_translate("MainWindow", "degrees"))
        self.lblRollSetpointLabel.setText(_translate("MainWindow", "TARGET SETPOINT"))
        self.txtRollSetpoint.setPlaceholderText(_translate("MainWindow", "Masukkan nilai roll..."))
        self.btnRollActivate.setText(_translate("MainWindow", "🚀 ACTIVATE ROLL CONTROL"))
        self.lblRollStatus.setText(_translate("MainWindow", "⚪ STATUS: INACTIVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRoll), _translate("MainWindow", "ROLL CONTROL"))
        
        # Pitch Control Tab
        self.lblPitchControlTitle.setText(_translate("MainWindow", "⬆️ Set Pitch Setpoint"))
        self.lblPitchCurrentLabel.setText(_translate("MainWindow", "CURRENT VALUE"))
        self.lblPitchCurrentValue.setText(_translate("MainWindow", "0.00"))
        self.lblPitchCurrentUnit.setText(_translate("MainWindow", "degrees"))
        self.lblPitchSetpointLabel.setText(_translate("MainWindow", "TARGET SETPOINT"))
        self.txtPitchSetpoint.setPlaceholderText(_translate("MainWindow", "Masukkan nilai pitch..."))
        self.btnPitchActivate.setText(_translate("MainWindow", "🚀 ACTIVATE PITCH CONTROL"))
        self.lblPitchStatus.setText(_translate("MainWindow", "⚪ STATUS: INACTIVE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPitch), _translate("MainWindow", "PITCH CONTROL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())